### ISSUE TITLE
npm ERR! Error: CERT_UNTRUSTED

### ISSUE THREAD

**Issue by fat84** [dest4/radio-playlist-generator#1]
hello i compile on ubuntu but this error on 2  servers 

root@radioserver:~/radio-playlist-generator# npm install
npm WARN package.json radio-playlist-generator@0.1.0 No repository field.
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/sqlite3
npm http GET https://registry.npmjs.org/webradio-metadata
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/sqlite3
npm http GET https://registry.npmjs.org/webradio-metadata
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/sqlite3
npm http GET https://registry.npmjs.org/webradio-metadata
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR!     at flow (_stream_readable.js:592:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-161-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /root/radio-playlist-generator
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/radio-playlist-generator/npm-debug.log
npm ERR! not ok code 0

help me please thanks   to fix it

**Comment by dest4** [comment]
Seems like a cert issue not under my control. The technical team of npmjs has probably handled this by now.
Is the problem still there?
