### ISSUE TITLE
not mp3 download

### ISSUE THREAD

**Issue by fat84** [dest4/radio-playlist-generator#3]
hello   i solved   this error
-01-14T04:43:48.088Z] info rpgen:  meta={"artist":"Le 5 | 7 : Lucie Barbarin","title":"L'info à 5h40"}
/root/Desktop/radio-playlist-generator/index.js:28
                                cb(null, meta);
                                  ^
TypeError: cb is not a function
    at Statement.<anonymous> (/root/Desktop/radio-playlist-generator/index.js:28:5)

but mp3  not downloading   
any   help?  thanks

**Comment by dest4** [comment]
A change in a module broke the main routine. I fixed it https://github.com/dest4/radio-playlist-generator/commit/8103d8e6ba26b55cd2944446f804777ad4504342
